# Generated by Django 5.2.13 on 2026-04-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('quantidade_minima', models.IntegerField(default=5)),
                ('unidade_medida', models.CharField(choices=[('Unidade', 'Unidade'), ('Metros', 'Metros'), ('Pacote', 'Pacote')], default='Unidade', max_length=20)),
                ('localizacao_fisica', models.CharField(max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categoria')),
            ],
        ),
    ]
