# Generated by Django 5.2.13 on 2026-04-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
