# Generated by Django 5.2.13 on 2026-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemestoque_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='localizacao_fisica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
