# Generated by Django 5.2.13 on 2026-04-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_itemestoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categoria'),
        ),
    ]
