# Generated by Django 5.2.13 on 2026-05-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemestoque_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=200)),
                ('tipo_equipamento', models.CharField(choices=[('SW', 'Switch'), ('AP', 'Access Point'), ('SRV', 'Servidor'), ('OUT', 'Outro')], default='OUT', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='inventory.itemestoque')),
            ],
            options={
                'verbose_name_plural': 'Saídas de Estoque',
            },
        ),
    ]
