# Generated by Django 5.2.13 on 2026-05-05 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_saidaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
