# Generated by Django 5.2.13 on 2026-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itemestoque_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
