# Generated by Django 5.2.13 on 2026-05-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_cftv_outros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Categorias'},
        ),
    ]
