# Generated by Django 6.0.5 on 2026-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_categoria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('ADM', 'Administrativo'), ('PED', 'Pedagógico'), ('INF', 'Informática'), ('OUT', 'Outro')], default='OUT', max_length=3)),
                ('solicitante', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('defeito', models.TextField()),
                ('laudo', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('itens', models.ManyToManyField(blank=True, to='inventory.itemestoque')),
            ],
            options={
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
