# Generated by Django 5.2.14 on 2026-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='laudo_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Laudo Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_MANUTENCAO', 'Em Manutenção'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Entregue')], default='ABERTO', max_length=20),
        ),
    ]
