# Generated by Django 5.2.14 on 2026-05-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_ordemservico_data_saida_ordemservico_laudo_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='baixa_efetuada',
            field=models.BooleanField(default=False, verbose_name='Baixa de Estoque já efetuada'),
        ),
    ]
