# Generated by Django 5.2.14 on 2026-05-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_ordemservico_baixa_efetuada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='baixa_efetuada',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='estoque_debitado',
            field=models.BooleanField(default=False, verbose_name='Estoque já debitado'),
        ),
    ]
