# Generated by Django 5.2.13 on 2026-04-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nvr_channel', models.IntegerField(blank=True, null=True, verbose_name='Canal no NVR')),
                ('tecnologia', models.CharField(choices=[('IP', 'IP'), ('AN', 'Analógica')], default='IP', max_length=50)),
                ('localizacao', models.CharField(max_length=200)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SW', 'Switch'), ('AP', 'Access Point'), ('SRV', 'Servidor'), ('OUT', 'Outro')], max_length=3)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('localizacao', models.CharField(help_text='Ex: Sala 05, Bloco B', max_length=200)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
