# Generated by Django 5.2.13 on 2026-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(blank=True, verbose_name='Detalhes')),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta'), ('Critica', 'Crítica (Urgente)')], default='Media', max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Execução', 'Em Execução'), ('Aguardando', 'Aguardando Terceiro'), ('Concluido', 'Concluído')], default='Pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('previsao_conclusao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
