# Generated by Django 5.2.13 on 2026-04-14 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Critica', 'Critica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
