# Generated by Django 5.2.13 on 2026-04-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarefa_data_conclusao_tarefa_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao_detalhada',
            field=models.TextField(blank=True, null=True, verbose_name='Relato Técnico'),
        ),
    ]
