# Generated by Django 5.2.13 on 2026-04-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva'), ('Instalação', 'Instalação')], default='Corretiva', max_length=20)),
                ('descricao', models.TextField(verbose_name='O que foi feito?')),
                ('tecnico', models.CharField(default='Romário Rodrigues', max_length=100)),
                ('custo_material', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.camera')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.equipamento')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
            },
        ),
    ]
